### ISSUE TITLE
texstudio crashes on options save

### ISSUE THREAD

**Issue by linderd** [texstudio-org/texstudio#1103]
### Environment
- TeXstudio: 2.12.22 
- Qt: 5.13.2
- OS: Fedora 32 (kernel 5.6.12)
- TeX distribution: texlive

### Expected behavior

Trying to save Options (I don't even have to change something)

### Actual behavior

Crashes in the moment when I click OK in Options

### How to reproduce

- install texstudio from dnf
- open options
- click OK

Working with a normal LaTeX-File actually works, I just wanted to change from bibtex to biber.

I already backtraced the segmentation fault:

~~~~
gdb texstudio
GNU gdb (GDB) Fedora 9.1-5.fc32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from texstudio...
Reading symbols from .gnu_debugdata for /usr/bin/texstudio...
(No debugging symbols found in .gnu_debugdata for /usr/bin/texstudio)
Missing separate debuginfos, use: dnf debuginfo-install texstudio-2.12.22-2.fc32.x86_64
(gdb) 
(gdb) backtrace
No stack.
(gdb) run
Starting program: /usr/bin/texstudio 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe5ca7700 (LWP 25063)]
QSocketNotifier: Can only be used with threads started with QThread
[New Thread 0x7fffdffff700 (LWP 25064)]
[New Thread 0x7fffdf7fe700 (LWP 25065)]
[New Thread 0x7fffdeffd700 (LWP 25066)]
[New Thread 0x7fffde7fc700 (LWP 25067)]
[New Thread 0x7fffcffff700 (LWP 25068)]
[New Thread 0x7fffceff9700 (LWP 25069)]
[New Thread 0x7fffce7f8700 (LWP 25070)]
[New Thread 0x7fffcdff7700 (LWP 25071)]
[New Thread 0x7fffcd7f6700 (LWP 25072)]
[New Thread 0x7fffccff5700 (LWP 25073)]
[New Thread 0x7fffc329d700 (LWP 25074)]
[New Thread 0x7fffc2a9c700 (LWP 25075)]
[New Thread 0x7fffc229b700 (LWP 25076)]
[New Thread 0x7fffc1a9a700 (LWP 25077)]
[New Thread 0x7fffc1299700 (LWP 25078)]
[New Thread 0x7fffc0a98700 (LWP 25079)]
[New Thread 0x7fff8bfff700 (LWP 25080)]
[New Thread 0x7fff8b7fe700 (LWP 25081)]
[New Thread 0x7fff8affd700 (LWP 25082)]
[New Thread 0x7fff8a7fc700 (LWP 25083)]
[New Thread 0x7fff89ffb700 (LWP 25084)]
[New Thread 0x7fff897fa700 (LWP 25085)]
[New Thread 0x7fff88ff9700 (LWP 25086)]
[New Thread 0x7fff6bfff700 (LWP 25087)]
[New Thread 0x7fff6b0e8700 (LWP 25088)]
[New Thread 0x7fff6a8e7700 (LWP 25089)]
[Detaching after fork from child process 25090]
[Thread 0x7fff6a8e7700 (LWP 25089) exited]

Thread 1 "texstudio" received signal SIGSEGV, Segmentation fault.
0x00005555559caa0c in LatexCompleter::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
(gdb) backtrace
#0  0x00005555559caa0c in LatexCompleter::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#1  0x00007ffff6a18c21 in QMetaObject::activate(QObject*, int, int, void**) () from /lib64/libQt5Core.so.5
#2  0x00007ffff6a19352 in QObject::event(QEvent*) () from /lib64/libQt5Core.so.5
#3  0x00007ffff7749e76 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib64/libQt5Widgets.so.5
#4  0x00007ffff69f28a0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib64/libQt5Core.so.5
#5  0x00007ffff77a8681 in QWidgetWindow::event(QEvent*) () from /lib64/libQt5Widgets.so.5
#6  0x00007ffff7749e76 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib64/libQt5Widgets.so.5
#7  0x00007ffff69f28a0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib64/libQt5Core.so.5
#8  0x00007ffff69f5b43 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /lib64/libQt5Core.so.5
#9  0x00007ffff6a3e187 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () from /lib64/libQt5Core.so.5
#10 0x00007ffff51b97cf in g_main_context_dispatch () from /lib64/libglib-2.0.so.0
#11 0x00007ffff51b9b58 in g_main_context_iterate.constprop () from /lib64/libglib-2.0.so.0
#12 0x00007ffff51b9c23 in g_main_context_iteration () from /lib64/libglib-2.0.so.0
#13 0x00007ffff6a3dc06 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /lib64/libQt5Core.so.5
#14 0x00007ffff69f121b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib64/libQt5Core.so.5
#15 0x00007ffff69f8df6 in QCoreApplication::exec() () from /lib64/libQt5Core.so.5
#16 0x0000555555637a32 in main ()
~~~~

**Comment by linderd** [comment]
ok, same issue is already here https://github.com/texstudio-org/texstudio/issues/1100
