### ISSUE TITLE
Closing the internal terminal causes a crash

### ISSUE THREAD

**Issue by MeanSquaredError** [texstudio-org/texstudio#1251]
@axkibe 

Closing the internal terminal in TXS causes TXS to crash.
How to reproduce:
1. Build TXS with support for the internal terminal.
2. Start TXS.
3. Click on the [Terminal] tab on the bottom panel.
4. Close the terminal in some way, e.g. by pressing `CTRL+D` or by typing `exit<Enter>`
5. TXS will activate the crash handler.

Disabling `CTRL+D` is not a proper fix, since there are various other ways to close the terminal e.g. by typing `exit<Enter>` and there are probably other ways too.

I guess one possible solution would be add some code that will detect when the terminal closes and to restart the terminal in these cases.

**Comment by axkibe** [comment]
I can take a look at it in the upcoming days. As far as I remember it is designed to restart the terminal in case the process ends and I did test exit, Ctrl+D and kill situations, must have been gotten broken somewhere.

**Comment by MeanSquaredError** [comment]
This is the backtrace + frame 1 where the actual crash happens
```
(gdb) bt
#0  0x000055555702a010 in ?? ()
#1  0x00005555558a55ed in TerminalWidget::initQTermWidget (this=0x555556db15e0) at ../src/toolwidgets.cpp:196
#2  0x00007ffff689ffb0 in doActivate<false> (sender=0x55555702a010, signal_index=7, argv=0x7fffffffcc10) at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:395
#3  0x00007ffff689ffb0 in doActivate<false> (sender=0x55555787c3a0, signal_index=4, argv=0x7fffffffccf0, argv@entry=0x0) at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:395
#4  0x00007ffff689a7f8 in QMetaObject::activate (sender=sender@entry=0x55555787c3a0, m=m@entry=0x7ffff7f94600 <Konsole::Session::staticMetaObject>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x0)
    at kernel/qobject.cpp:3930
#5  0x00007ffff7f78527 in Konsole::Session::finished (this=this@entry=0x55555787c3a0) at /usr/src/debug/qtermwidget-0.14.1-4.fc32.x86_64/x86_64-redhat-linux-gnu/lib/moc_Session.cpp:433
#6  0x00007ffff7f5e9e4 in Konsole::Session::done (this=0x55555787c3a0, exitStatus=0) at /usr/src/debug/qtermwidget-0.14.1-4.fc32.x86_64/lib/Session.cpp:612
#7  0x00007ffff689ffb0 in doActivate<false> (sender=0x555557eb9380, signal_index=11, argv=argv@entry=0x7fffffffce80) at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:395
#8  0x00007ffff689a7f8 in QMetaObject::activate (sender=sender@entry=0x555557eb9380, m=m@entry=0x7ffff6b26e40 <QProcess::staticMetaObject>, local_signal_index=local_signal_index@entry=2, argv=argv@entry=0x7fffffffce80)
    at kernel/qobject.cpp:3930
#9  0x00007ffff6804573 in QProcess::finished (this=this@entry=0x555557eb9380, _t1=<optimized out>, _t2=<optimized out>) at .moc/moc_qprocess.cpp:339
#10 0x00007ffff680815a in QProcessPrivate::_q_processDied (this=0x5555579d61f0) at io/qprocess.cpp:1184
#11 0x00007ffff680826e in QProcess::qt_static_metacall (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=0x7fffffffd020) at io/qprocess.h:301
#12 0x00007ffff689ffb0 in doActivate<false> (sender=0x5555570b11c0, signal_index=3, argv=argv@entry=0x7fffffffd020) at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:395
#13 0x00007ffff689a7f8 in QMetaObject::activate (sender=sender@entry=0x5555570b11c0, m=m@entry=0x7ffff6b29220 <QSocketNotifier::staticMetaObject>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7fffffffd020)
    at kernel/qobject.cpp:3930
#14 0x00007ffff68a2f4c in QSocketNotifier::activated (this=this@entry=0x5555570b11c0, _t1=<optimized out>, _t2=...) at .moc/moc_qsocketnotifier.cpp:141
#15 0x00007ffff68a32f1 in QSocketNotifier::event (this=0x5555570b11c0, e=0x7fffffffd110) at kernel/qsocketnotifier.cpp:266
#16 0x00007ffff765e063 in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x5555570b11c0, e=0x7fffffffd110) at kernel/qapplication.cpp:3685
#17 0x00007ffff6870fc0 in QCoreApplication::notifyInternal2 (receiver=0x5555570b11c0, event=0x7fffffffd110) at ../../include/QtCore/../../src/corelib/kernel/qobject.h:153
#18 0x00007ffff68bd5d7 in socketNotifierSourceDispatch (source=0x5555562a0070) at kernel/qeventdispatcher_glib.cpp:107
#19 0x00007ffff4fcb78f in g_main_context_dispatch () from /lib64/libglib-2.0.so.0
#20 0x00007ffff4fcbb18 in g_main_context_iterate.constprop () from /lib64/libglib-2.0.so.0
#21 0x00007ffff4fcbbe3 in g_main_context_iteration () from /lib64/libglib-2.0.so.0
#22 0x00007ffff68bcb8b in QEventDispatcherGlib::processEvents (this=0x5555562b21a0, flags=...) at kernel/qeventdispatcher_glib.cpp:425
#23 0x00007ffff686f91b in QEventLoop::exec (this=this@entry=0x7fffffffd320, flags=..., flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:136
#24 0x00007ffff68775a6 in QCoreApplication::exec () at ../../include/QtCore/../../src/corelib/global/qflags.h:118
#25 0x000055555562f781 in main (argc=<optimized out>, argv=0x7fffffffd3a8) at ../src/main.cpp:222
(gdb) frame 1
#1  0x00005555558a55ed in TerminalWidget::initQTermWidget (this=0x555556db15e0) at ../src/toolwidgets.cpp:196
196             if (qTermWidget) delete qTermWidget;
```

The actual crash seems to happen here:
```
#1  0x00005555558a55ed in TerminalWidget::initQTermWidget (this=0x555556db15e0) at ../src/toolwidgets.cpp:196
196             if (qTermWidget) delete qTermWidget;
```
Looks like the crash happens when it tries to re-initialize the terminal, finds out that there is an old copy and tries to delete the old copy.

IIRC, @benibela did some changes to the terminal-handling code recently, so maybe it has something to do with these changes?

**Comment by MeanSquaredError** [comment]
OK, indeed it looks like the term widget gets deleted twice. The first time is here:
```
void TerminalWidget::qTermWidgetFinished()
{
        // in case the shell closed the widget is reinitiated
        delete qTermWidget;
        initQTermWidget();
}
```

OK, I will provide a PR with a fix shortly.
