### ISSUE TITLE
core dump at start

### ISSUE THREAD

**Issue by ashinpan** [texstudio-org/texstudio#3071]
### Environment
- TeXstudio:  Master
- Qt: 6.5.0
- OS: Linux Mint 21.1
- TeX distribution: texlive

### Expected behavior
Should open normally at the start

### Actual behavior
Fails with the following message:

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: offscreen, eglfs, minimalegl, linuxfb, xcb, minimal, vkkhrdisplay, wayland, wayland-egl, vnc.
Aborted (core dumped)

backtrace log:

(gdb) run
Starting program: /home/pan/bin/texstudio 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: offscreen, eglfs, minimalegl, linuxfb, xcb, minimal, vkkhrdisplay, wayland, wayland-egl, vnc.

Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737240731712) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, 
    threadid=140737240731712) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737240731712)
    at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737240731712, signo=signo@entry=6)
    at ./nptl/pthread_kill.c:89
#3  0x00007ffff55ee476 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/posix/raise.c:26
#4  0x00007ffff55d47f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff5c9a7d0 in qAbort() ()
   from /home/pan/Qt/6.5.0/gcc_64/lib/libQt6Core.so.6
#6  0x00007ffff5c9af38 in QMessageLogger::fatal(char const*, ...) const ()
   from /home/pan/Qt/6.5.0/gcc_64/lib/libQt6Core.so.6
#7  0x00007ffff6394f35 in ?? ()
   from /home/pan/Qt/6.5.0/gcc_64/lib/libQt6Gui.so.6
#8  0x00007ffff643319c in QGuiApplicationPrivate::createPlatformIntegration() () from /home/pan/Qt/6.5.0/gcc_64/lib/libQt6Gui.so.6
#9  0x00007ffff6433bf0 in QGuiApplicationPrivate::createEventDispatcher() ()
   from /home/pan/Qt/6.5.0/gcc_64/lib/libQt6Gui.so.6
#10 0x00007ffff5d33046 in QCoreApplicationPrivate::init() ()
   from /home/pan/Qt/6.5.0/gcc_64/lib/libQt6Core.so.6
#11 0x00007ffff6436f00 in QGuiApplicationPrivate::init() ()
   from /home/pan/Qt/6.5.0/gcc_64/lib/libQt6Gui.so.6
--Type <RET> for more, q to quit, c to continue without paging--c
#12 0x00007ffff6dbeca9 in QApplicationPrivate::init() () from /home/pan/Qt/6.5.0/gcc_64/lib/libQt6Widgets.so.6
#13 0x00005555560fcdee in QtSingleApplication::QtSingleApplication(QString const&, int&, char**) ()
#14 0x0000555555efb140 in TexstudioApp::TexstudioApp(QString&, int&, char**) ()
#15 0x0000555555efc30e in main ()
(gdb)

**Comment by sunderme** [comment]
as this is not a binary from us, I am not really able to debug.
I can only say, that txs compiled against QT 6.5 works fine on LXQt and Unbuntu (Gnome/Wayland).
