### ISSUE TITLE
Segfault when "Open Recent" -> Root Document.

### ISSUE THREAD

**Issue by axkibe** [texstudio-org/texstudio#937]
I can reproduce this crash within minutes, but it's not 100% always the same.
Start by setting two explicit root documents (had it in different directories)
Then close all tabs in the editor, Then click File->Open Recent->Root Document->M: or N:
Do this with both documents, close the tabs in the editor again, repeat a few times, it will soon crash.

Full gdb backtrace:
```
Thread 1 "texstudio" received signal SIGSEGV, Segmentation fault.
0x00007ffff7601fd3 in QWidgetPrivate::reparentFocusWidgets(QWidget*) ()
   from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
(gdb) backtrace
#0  0x00007ffff7601fd3 in QWidgetPrivate::reparentFocusWidgets(QWidget*) ()
   from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#1  0x00007ffff7608802 in QWidget::setParent(QWidget*, QFlags<Qt::WindowType>) ()
   from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#2  0x00007ffff75e5f13 in QLayout::addChildWidget(QWidget*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#3  0x00007ffff75ebccd in QStackedLayout::insertWidget(int, QWidget*) ()
   from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007ffff77887b6 in QTabWidget::insertTab(int, QWidget*, QIcon const&, QString const&) ()
   from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff7788887 in QTabWidget::insertTab(int, QWidget*, QString const&) ()
   from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x0000555555b72152 in TxsTabWidget::insertEditor (this=0x555556e11c10, edView=0x55555891d1e0, pos=-1, 
    asCurrent=true) at src/txstabwidget.cpp:173
#7  0x000055555594c044 in Editors::insertEditor (this=0x555556968a10, edView=0x55555891d1e0, 
    tabWidget=0x555556e11c10, pos=-1, asCurrent=true) at src/editors.cpp:144
#8  0x000055555594bdd8 in Editors::insertEditor (this=0x555556968a10, edView=0x55555891d1e0, index=0, 
    asCurrent=true) at src/editors.cpp:90
#9  0x000055555594ddbc in Editors::moveToTabGroup (this=0x555556968a10, edView=0x55555891d1e0, target=0x0, 
    targetIndex=0) at src/editors.cpp:485
#10 0x000055555594bf14 in Editors::moveEditor (this=0x555556968a10, edView=0x55555891d1e0, 
    pos=Editors::GroupFront) at src/editors.cpp:113
#11 0x0000555555b2b886 in Texstudio::masterDocumentChanged (this=0x5555568e8370, doc=0x555558e4cac0)
    at src/texstudio.cpp:7217
#12 0x0000555555e6d259 in Texstudio::qt_static_metacall (_o=0x5555568e8370, _c=QMetaObject::InvokeMetaMethod, 
    _id=314, _a=0x7fffffffc790) at .moc/moc_texstudio.cpp:2017
#13 0x00007ffff67a2866 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x0000555555e5d79b in LatexDocuments::masterDocumentChanged (this=0x5555568e84b0, _t1=0x555558e4cac0)
    at .moc/moc_latexdocument.cpp:1275
#15 0x00005555559ad0b4 in LatexDocuments::setMasterDocument (this=0x5555568e84b0, document=0x555558e4cac0)
    at src/latexdocument.cpp:1956
#16 0x0000555555afc7c5 in Texstudio::load (this=0x5555568e8370, f=..., asProject=true, hidden=false, 
    recheck=true, dontAsk=false) at src/texstudio.cpp:1947
#17 0x0000555555b06d6e in Texstudio::fileOpenRecentProject (this=0x5555568e8370) at src/texstudio.cpp:3130
#18 0x0000555555e6a890 in Texstudio::qt_static_metacall (_o=0x5555568e8370, _c=QMetaObject::InvokeMetaMethod, 
    _id=63, _a=0x7fffffffd320) at .moc/moc_texstudio.cpp:1746
#19 0x00007ffff67a2866 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007ffff75c2f02 in QAction::triggered(bool) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
--Type <RET> for more, q to quit, c to continue without paging--c
#21 0x00007ffff75c5520 in QAction::activate(QAction::ActionEvent) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff77359dc in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff773cf00 in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff773de6b in QMenu::mouseReleaseEvent(QMouseEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007ffff76074d8 in QWidget::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007ffff77402fb in QMenu::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007ffff75c94c1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00007ffff75d0bb8 in QApplication::notify(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007ffff67794f9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00007ffff75cfee9 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#31 0x00007ffff7622393 in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#32 0x00007ffff7624b5e in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#33 0x00007ffff75c94c1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#34 0x00007ffff75d0970 in QApplication::notify(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#35 0x00007ffff67794f9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#36 0x00007ffff6ff7ff3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#37 0x00007ffff6ff9e75 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#38 0x00007ffff6fd406b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#39 0x00007ffff14d940b in ?? () from /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#40 0x00007ffff67781cb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#41 0x00007ffff67801a2 in QCoreApplication::exec() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#42 0x0000555555a239ee in main (argc=1, argv=0x7fffffffe198) at src/main.cpp:219
(gdb) 
```

### Environment
- TeXstudio: 2.1.22 & 3.00.00, above backtrace is at the time of writing from current git HEAD (b124ef00e5cc95197c8761aeeb1744ea47a8280c)
- Qt: Qt 5.11.3 D
- OS: linux debian buster
- TeX distribution: texlive

**Comment by axkibe** [comment]
Different backtrace, same way to raise it (keep closing the tabs in the editor and reopening recent root documents, alternating between to recents)
```
#0  0x0000000000000060 in ?? ()
#1  0x00007ffff6782729 in QMetaObject::cast(QObject const*) const ()
   from /lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00005555559eca13 in qobject_cast<LatexDocument const*> (object=0x555558a8d520)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:504
#3  0x00005555559deab8 in LatexEditorView::documentContentChanged (this=0x555557cd0380, linenr=0, 
    count=0) at src/latexeditorview.cpp:1926
#4  0x00005555559ad05a in LatexDocuments::setMasterDocument (this=0x5555568e8ae0, 
    document=0x555558a8d520) at src/latexdocument.cpp:1952
#5  0x0000555555afc7c5 in Texstudio::load (this=0x5555568e89a0, f=..., asProject=true, 
    hidden=false, recheck=true, dontAsk=false) at src/texstudio.cpp:1947
#6  0x0000555555b06d6e in Texstudio::fileOpenRecentProject (this=0x5555568e89a0)
    at src/texstudio.cpp:3130
#7  0x0000555555e6a890 in Texstudio::qt_static_metacall (_o=0x5555568e89a0, 
    _c=QMetaObject::InvokeMetaMethod, _id=63, _a=0x7fffffffd320) at .moc/moc_texstudio.cpp:1746
#8  0x00007ffff67a2866 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007ffff75c2f02 in QAction::triggered(bool) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ffff75c5520 in QAction::activate(QAction::ActionEvent) ()
   from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff77359dc in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff773cf00 in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff773de6b in QMenu::mouseReleaseEvent(QMouseEvent*) ()
   from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff76074d8 in QWidget::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff77402fb in QMenu::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff75c94c1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff75d0bb8 in QApplication::notify(QObject*, QEvent*) ()
   from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff67794f9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007ffff75cfee9 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff7622393 in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff7624b5e in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff75c94c1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff75d0970 in QApplication::notify(QObject*, QEvent*) ()
--Type <RET> for more, q to quit, c to continue without paging--c
   from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff67794f9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007ffff6ff7ff3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#26 0x00007ffff6ff9e75 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#27 0x00007ffff6fd406b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#28 0x00007ffff14d940b in ?? () from /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#29 0x00007ffff67781cb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00007ffff67801a2 in QCoreApplication::exec() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x0000555555a239ee in main (argc=1, argv=0x7fffffffe198) at src/main.cpp:219
```

**Comment by sunderme** [comment]
not sure why you use explicit root document. The automatism should work fine for detecting root/child relations.
The crash should be fixed.

**Comment by axkibe** [comment]
Thanks! I'll try it out tomorrow.

About the why, well it's not me directly, it's my boss whom I recently convinced to switch over from Kile after many year of using that and he is used to explicit root document setting, especially when he copies over text block from previous papers but always wants to compile the current project anyway, no matter which tab is selected in the editor. It's nice this well known feature is there from convenience, even if not strictly necessary.

**Comment by axkibe** [comment]
Just tested it out, cannot produce it anymore. Thanks!
